[sgb:stix:indicator]
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
KV_MODE = json
TIME_PREFIX = "modified":\s*"
TIME_FORMAT = %Y-%m-%dT%H:%M:%S
MAX_TIMESTAMP_LOOKAHEAD = 32
TRUNCATE = 65536
category = Structured
description = SGB TAXII feed STIX 2.1 indicator (flattened JSON)
